---
title: "Global Warming: A Data Visualisation Dashboard (By Gian Atmaja)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

# Introduction {.sidebar}
-------------------------------------------------------
Hi there! Thanks for taking your time to view this dashboard.  

This dashboard presents information from various sources regarding different aspects of global warming.  

First, viewers can see a direct representation of global warming itself, which is shown by the rise in global temperature. Then, visualisations of the emission of greenhouse gases, which is the leading cause of global warming, are presented. Finally, a couple effects of global warming are included.  

The dashboard uses open source data from various sources, such as:

*[Berkeley Earth](http://berkeleyearth.org/data/)

*[Gapminder](https://www.gapminder.org/data/)

*[Datahub](https://datahub.io/)

*[World Bank Open Data](https://data.worldbank.org/)
  
The codes used for this dashboard, including those used in the data wrangling and individual plots, can be found in my [GitHub repository](https://github.com/Gianatmaja/Global-Warming-Dashboard). 

```{r setup, include=FALSE}
#Load the required libraries
library(flexdashboard)
library(dplyr)
library(tibble)
library(countrycode)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(plotly)
library(viridis)
library(RColorBrewer)
library(ggsci)

#Reading the data files
AvgGloTemp = read.table("AverageGlobalTemp.txt", sep = "", skip = 69)  
AvgGloTemp = AvgGloTemp[,1:3]
names(AvgGloTemp) = c("Year","Month","Anomaly")
Sea_Level = read.csv("Sea_Level_GMSL.csv", header = T, check.names = F)
Extreme_temp = read.csv("Extreme_temp.csv", skip = 1, header = F,check.names = F)
CO2.Emi = read.csv("CO2_Emissions.csv", header = T, check.names = F)
Methane.Emi = read.csv("Methane_Emissions.csv",skip = 4, header = T, check.names = F)
NO_Emi = read.csv("NO_Emissions.csv", skip = 4, header = T, check.names = F)
```

Row
-----------------------------------------------------------------------

### Average Global Land Temperature (1850-2013)

```{r}
#Cleaning
AvgGloTemp = AvgGloTemp[1275:3239,]
AvgGloTemp_yearly =  AvgGloTemp %>% group_by(Year) %>% summarise(Avg = mean(Anomaly))

AvgGloTemp_yearly$Avg = AvgGloTemp_yearly$Avg + 8.7
GloTemp = AvgGloTemp_yearly

#Find trend
Increase = GloTemp$Avg[2:164] - GloTemp$Avg[1:163]
GloTemp$Difference = c(0,Increase)
for (i in 1:164){
  if(GloTemp$Difference[i] <= 0){
    GloTemp$Trend[i] = "Not increasing"
  }else{
    GloTemp$Trend[i] = "Increasing"
  }
}
GloTemp$Difference = abs(GloTemp$Difference)

#Plotting
P1 = ggplot(data = GloTemp) + geom_point(aes(x = Year, y = Avg, size = Difference, col = Trend), alpha = I(4/5)) + 
  geom_smooth(aes(x = Year, y = Avg), col = "black", se = F, lty = 2) + theme_hc() +
  theme(axis.title = element_text(face = "bold")) +  xlab("") + 
  ylab("Temperature\n")  + scale_color_manual(values = brewer.pal(3,"RdYlBu")[c(1,3)])

#Interactivity
Plot1 = ggplotly(P1) %>% 
  layout(title = list(text = paste0("<sup>", "Measured in degrees celcius; Raw data source: berkeleyearth.org/data/", "</sup>"))) %>%
  layout(title = list(orientation = "h", x = 0.01, y = 0.95)) %>%
  layout(legend = list(orientation = "h", x = 0.3, y = -0.35))
Plot1
```

### CO2 Emissions (1860-2014)

```{r}
CO2.Emi.2 = CO2.Emi[,c(1,111:265)]

#Find region
CO2.Emi.2$continent = countrycode(sourcevar = CO2.Emi.2[,"country"], origin = "country.name", destination = "continent")

#Cleaning
CO2.Emi.2 = CO2.Emi.2[,c(1,157,2:156)]

CO2.Emi.tidy = CO2.Emi.2 %>%
  gather(year, emission, '1860':'2014')

CO2.Emi.tidy[is.na(CO2.Emi.tidy)] = 0
CO2.Emi.continent = CO2.Emi.tidy %>%  group_by(year, continent) %>% summarise(total = sum(emission))

#Plotting
P3 = ggplot(data = CO2.Emi.continent, aes(x = year, y = total, fill = continent, group = continent)) + 
  geom_area() + scale_x_discrete(breaks = seq(1860,2010,20)) +
  theme_minimal() + xlab("") + ylab("Total\n") + labs(fill = "Continent") +
  theme(axis.title = element_text(face = "bold")) + scale_fill_npg()
Plot3 = ggplotly(P3) %>% 
  layout(title = list(text = paste0("<sup>", "Measured in kilotonnes; Raw data source: gapminder.org/data/", "</sup>"))) %>%
  layout(title = list(orientation = "h", x = 0.01, y = 0.95)) %>%
  layout(legend = list(orientation = "h", x = 0.08, y = -0.3))
Plot3
```


Row
-----------------------------------------------------------------------

### Global Cumulative Sea Level Change (1993-2015)

```{r}
Month = rep(1:12,23)
Month = Month[1:266]
Year = rep(1993:2015,each=12)
Year = Year[1:266]
Mean_Sea_Level = data.frame(cbind(Year, Month, Sea_Level$GMSL))
names(Mean_Sea_Level) = c("Year", "Month", "GMSL")
Mean_Sea_Level = Mean_Sea_Level %>% group_by(Year) %>% summarise(Change = last(GMSL))
Rise = Mean_Sea_Level$Change - Mean_Sea_Level$Change[c(1,1:22)]
Mean_Sea_Level = data.frame(cbind(Mean_Sea_Level$Year, Mean_Sea_Level$Change, Rise))
Mean_Sea_Level$Rise[1] = NA
names(Mean_Sea_Level) = c("Year", "Cumulative_change", "One_year_rise")
P2 = ggplot(data = Mean_Sea_Level) + geom_bar(aes(x = Year, y = Cumulative_change), stat = "identity", fill = "steelblue2") +
  geom_line(aes(x = Year, y = Cumulative_change), col = "royalblue4") + geom_point(aes(x = Year, y = Cumulative_change, One_year_rise = One_year_rise)) + xlab("") + ylab("Change\n") + theme_minimal()
P2
Plot2 = ggplotly(P2) %>% 
  layout(title = list(text = paste0("<sup>", "Measured in mm; Raw data source: datahub.io/", "</sup>"))) %>%
  layout(title = list(orientation = "h", x = 0.01, y = 0.96))
Plot2
```

### Methane & NO Emissions (1979-2012)

```{r}
#Region area
Methane.Emi$continent = countrycode(sourcevar = Methane.Emi[,"Country Name"], origin = "country.name", destination = "continent")

#Cleaning for methane dataset
Methane.Emi = Methane.Emi[,c(1,66,2:65)]

Index = which(is.na(Methane.Emi$continent) == T)
Methane.Emi = Methane.Emi[-Index,]

Methane.Emi.tidy = Methane.Emi %>%
  gather(year, emission, '1960':'2019')
Methane.Emi.tidy = Methane.Emi.tidy[,c(1,2,7,8)]

Methane.Emi.tidy[is.na(Methane.Emi.tidy)] = 0

Methane.Emi.tidy = Methane.Emi.tidy %>% group_by(year) %>% summarise(emission = sum(emission))
Methane.Emi.tidy = Methane.Emi.tidy[11:53,]

#Cleaning for NO dataset
NO_Emi$continent = countrycode(sourcevar = NO_Emi[,"Country Name"], origin = "country.name", destination = "continent")
NO_Emi = NO_Emi[,c(1,66,2:65)]

Index2 = which(is.na(NO_Emi$continent) == T)
NO_Emi = NO_Emi[-Index2,]

NO_Emi.tidy = NO_Emi %>%
  gather(year, emission, '1960':'2019')
NO_Emi.tidy = NO_Emi.tidy[,c(1,2,7,8)]

NO_Emi.tidy[is.na(NO_Emi.tidy)] = 0

NO_Emi.tidy = NO_Emi.tidy %>% group_by(year) %>% summarise(emission = sum(emission))
NO_Emi.tidy = NO_Emi.tidy[11:53,]

#Joning data
A = Methane.Emi.tidy$emission
B = NO_Emi.tidy$emission

X = rep(1970:2012,each = 2)
Y = vector("numeric", 86)
Z = rep(c("Methane","NO"), 43)

for (i in 1:86){
  if(i %% 2 == 0){
    a = i/2
    Y[i] = B[a]
  }else{
    a = (i+1)/2
    Y[i] = A[a]
  }
}

NO_CH4_Year = cbind(X,Y,Z)
NO_CH4_Year = data.frame(NO_CH4_Year)
names(NO_CH4_Year) = c("Year","Emission","Gas")

#Plotting
P4 = ggplot(data = NO_CH4_Year) + geom_line(aes(x = Year, y = Emission, col = Gas, group = Gas)) + scale_x_discrete(breaks = seq(1970,2010,10)) + 
  scale_y_discrete(breaks = seq(2000000,8000000,2000000)) + xlab("Year\n") + 
  ylab("Emission\n") + theme_excel_new()
Plot4 = ggplotly(P4)%>% 
  layout(title = list(text = paste0("<sup>", "Measured in kilotonnes; Raw data source: data.worldbank.org/", "</sup>"))) %>%
  layout(title = list(orientation = "h", x = 0.01, y = 0.95)) %>%
  layout(legend = list(orientation = "h", x = 0.3, y = -0.25))
Plot4
```

### Countries Reporting Extreme Temperatures


```{r}
#Cleaning
Extreme_temp_matrix = matrix(0,68,2)
for (i in 1:39){
  Index3 = which(is.na(Extreme_temp[,i]) == T)
  Extreme_temp[Index3,i] = 0
}
for (j in 1:68){
  Extreme_temp_matrix[j,1] = sum(Extreme_temp[j,2:30])
}
for (j in 1:68){
  Extreme_temp_matrix[j,2] = sum(Extreme_temp[j,31:39])
}
A = length(which(Extreme_temp_matrix[,1] == 0))
B = length(which(Extreme_temp_matrix[,2] == 0))
Count_ET_matrix = matrix(c(A,B,68-A,68-B), nrow = 2, ncol = 2, byrow = T)
#first row = countries not reporting (1971-1999 for 1st column and 2000-2008 for 2nd column)
#second row = countries reporting (1971-1999 for 1st column and 2000-2008 for 2nd column)

Period = rep(c("1971-1999","2000-2008"),each = 2)
Number = c(35,33,57,11)
Prop = c(35/68,33/68,57/68,11/68)
Percentage = round(Prop*100,0)
Category = rep(c("Reporting", "Not reporting"),2)
ET_Final = data.frame(cbind(Period, Number, Percentage, Category))
ET_Final$Number = as.integer(as.character(ET_Final$Number))

#Plotting
P5 = ggplot(data = ET_Final) + geom_bar(aes(x = Period, y = Number, Percentage = Percentage, fill = Category, group = Category), stat = "identity", alpha = I(3/5)) +
  ylab("Number of countries\n") + xlab("") + scale_fill_futurama() + theme_pander()
Plot5 = ggplotly(P5) %>% 
  layout(title = list(text = paste0("<sup>", "Raw data source: gapminder.org/data/", "</sup>"))) %>%
  layout(title = list(orientation = "h", x = -0.03, y = 0.975)) %>%
  layout(legend = list(orientation = "h", x = 0.2, y = -0.3))
Plot5
```



